"""empty message

Revision ID: 5cf4939141ef
Revises: d1d82778a599
Create Date: 2024-12-21 01:13:39.536848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cf4939141ef'
down_revision = 'd1d82778a599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_approval',
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('income', sa.Float(), nullable=False),
    sa.Column('loan_amount', sa.Float(), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=False),
    sa.Column('loan_status', sa.String(length=20), nullable=False),
    sa.Column('asset_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('loan_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_approval')
    # ### end Alembic commands ###
