"""empty message

Revision ID: 658f4dd0e702
Revises: fbc46c69f25b
Create Date: 2024-12-20 21:21:05.164748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658f4dd0e702'
down_revision = 'fbc46c69f25b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_approval',
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('income', sa.Float(), nullable=False),
    sa.Column('loan_amount', sa.Float(), nullable=False),
    sa.Column('assets_value', sa.Float(), nullable=False),
    sa.Column('loan_status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('loan_id')
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('date_created', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('loan_approval')
    # ### end Alembic commands ###
