"""Initial migration

Revision ID: c4d50a7d820b
Revises: 658f4dd0e702
Create Date: 2024-12-20 22:56:13.250779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d50a7d820b'
down_revision = '658f4dd0e702'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_approval', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credit_score', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('asset_value', sa.Float(), nullable=False))
        batch_op.drop_column('assets_value')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_approval', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('assets_value', sa.FLOAT(), nullable=False))
        batch_op.drop_column('asset_value')
        batch_op.drop_column('credit_score')

    # ### end Alembic commands ###
