"""empty message

Revision ID: d1d82778a599
Revises: c4d50a7d820b
Create Date: 2024-12-21 00:43:03.613285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1d82778a599'
down_revision = 'c4d50a7d820b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_loan_approval')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_loan_approval',
    sa.Column('loan_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('assets_value', sa.FLOAT(), nullable=False),
    sa.Column('income', sa.FLOAT(), nullable=False),
    sa.Column('loan_amount', sa.FLOAT(), nullable=False),
    sa.Column('loan_status', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('loan_id')
    )
    # ### end Alembic commands ###
